### ISSUE TITLE
Remote utils should pass EXCLUDE_PATTERNS to the checksum tasks.

### ISSUE THREAD

**Issue by junhaoliao** [y-scope/yscope-dev-utils#68]
### Bug

as the title suggests

the checksum tasks in the remote utils should also respect the EXCLUDE_PATTERNS arguments.

### yscope-dev-utils version

fd7c42dd7b59f8f4ab0eccba5078393e10cddb00

### Environment

```
junhao@GIGABYTE:~/workspace/clp$ task --version
3.44.0
```

### Reproduction steps

1. call task "yscope-dev-utils:remote:download-and-extract-tar" with `EXCLUDE_PATTERNS` specified
    ```
      log-viewer:
        vars:
          LOG_VIEWER_OUTPUT_DIR: "{{.G_WEBUI_SRC_DIR}}/yscope-log-viewer"
        deps:
          - "utils:init"
        cmds:
          - task: "yscope-dev-utils:remote:download-and-extract-tar"
            vars:
              CHECKSUM_FILE: "{{.G_DEPS_LOG_VIEWER_CHECKSUM_FILE}}"
              EXCLUDE_PATTERNS: ["node_modules"]
              FILE_SHA256: "de0600b505545f1bceb7ff5725941035f7c1dc875d08249d9b6d679e3ba77f26"
              OUTPUT_DIR: "{{.LOG_VIEWER_OUTPUT_DIR}}"
              TAR_FILE: "{{.G_BUILD_DIR}}/yscope-log-viewer.tar.gz"
              URL: "https://github.com/y-scope/yscope-log-viewer/archive/969ff35.tar.gz"
    ```
2. create files in "{{.G_WEBUI_SRC_DIR}}/yscope-log-viewer"/`node_modules`
3. rerun the task again and observe the file getting re-downloaded / re-extracted
